title: leeyh's dev blog
email: leeyh0216@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site for programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leeyh0216
github_username:  leeyh0216

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 5

